### ISSUE TITLE
Contact emails to participants after submitting

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-vision-zero#4]
Parse into Desk.com and then send a confirmation once per user (if we send an email for each location, it will be a lot of duplicates)

**Comment by fkh** [comment]
@fitnr what from address do you want to use? Ideally, it will be one you have easy access to, because we will need to verify it for mail delivery (we'll send an email and you have to click the link). 

Also, what from name?

**Comment by fitnr** [comment]
Ideally we would have a visionzero@ email address. For now, use `Vision Zero for NYC <socialmedia@dot.nyc.gov>`.

**Comment by fkh** [comment]
@fitnr please respond to the confirmation email from Postmark, postmarkapp.com

**Comment by fitnr** [comment]
@fkh done
