### ISSUE TITLE
Validate Twitter cards

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-vision-zero#46]
@fitnr, can you validate Twitter cards with the @NYC_DOT account, so we get Twitter cards with a summary for shared places -- like this https://twitter.com/StephanieCr8s/status/459009371284836352

Here's the validator link: https://dev.twitter.com/docs/cards/validation/validator

**Comment by fitnr** [comment]
It's not letting me, screenshot below.

For the image, can we use the appropriate "sticker" icon if we're on a /place page?

![screen shot 2014-04-30 at 2 19 13 pm](https://cloud.githubusercontent.com/assets/714125/2845218/ef478428-d093-11e3-9bd6-74154ea65581.png)

**Comment by atogle** [comment]
@fitnr There was a problem with the title not being set on place urls which I fixed this morning. I'll set the image url to the sticker icon before the end of the day, and we can deploy again after hours. Shouldn't have any trouble with Twitter cards at that point.

**Comment by atogle** [comment]
@fitnr Likely. If you try `visionzero.herokuapp.com` (without the place) it will probably work.

**Comment by fitnr** [comment]
@atogle That's approved and seems to be working, e.g. https://twitter.com/NYC_DOT/status/461233982525673473

**Comment by fitnr** [comment]
Now getting a crawler error from twitter. This is probably their problem, will try again later.

`Failed to crawl url, debugId: 3166802395846-341857`

**Comment by atogle** [comment]
@fitnr Yep, failed on openplans.org and google.com as well.

**Comment by fitnr** [comment]
@atogle It's been validated. One change: the twitter:image:src attribute needs to be an absolute, not a relative URL.
