### ISSUE TITLE
make other' submissions harder

### ISSUE THREAD

**Issue by fitnr** [openplans/shareabouts-vision-zero#47]
We're seeing people use "other" to complain about potholes and traffic. Even more frustrating, people are leaving "other" pins with no explanation.

Two suggestions to fix:
- The comment field is required if other is chosen
- The following text slides in when other is chosen: _Suggestions on this site will be used for a safety plan. Have a street defect or faded marking you would like repaired? [Contact DOT](http://www.nyc.gov/html/dot/html/contact/contact-form.shtml) or call [311](http://nyc.gov/311)._

**Comment by fkh** [comment]
@fitnr you can see this on the staging site at http://visionzero-dev.herokuapp.com/

**Comment by atogle** [comment]
Deployed.

**Comment by fitnr** [comment]
Looks good, thanks.
