### ISSUE TITLE
Add "About" page language

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-vision-zero#5]

**Comment by fitnr** [comment]
_Draft language for about page:_

The City of New York must no longer regard traffic crashes as mere “accidents,” but rather as preventable incidents that can be systematically addressed. No level of fatality on city streets is inevitable or acceptable. Vision Zero requires constant input and feedback from citizens and civic organizations.

This map asks for your input on the safety conditions that have been identified as leading contributors to traffic crashes. The information collected on this site will be used to guide proposals in borough-wide traffic safety plans, to be published in 2015.
[Learn more about Vision Zero](http://nyc.gov/visionzero).

Use [311](http://www.nyc.gov/311/) If you have a problem, such a street defect, that you require assistance with.

**Comment by fitnr** [comment]
_draft intro text_

Every year, approximately 4,000 New Yorkers are seriously injured and more than 250 are killed in traffic crashes. Being struck by a vehicle is the leading cause of injury-related death for children under 14, and the second leading cause for seniors. On average, vehicles seriously injure or kill a New Yorker every two hours.

Vision Zero is the City's goal for ending traffic deaths and injuries on our streets. To accomplish this, we need everyone’s participation and input.

Use this interactive map to share your experiences with city streets. Your knowledge will be used to create a traffic safety plan that will describe how to make each borough’s streets safer for everyone, whether walking, biking or driving.

[You're also invited to a Vision Zero workshop to share your ideas](http://www.nyc.gov/html/visionzero/pages/dialogue/events.html).

We’re gathering feedback on these safety conditions:
• [black icon] Not enough time to cross 
• [dark green icon] Double parking 
• [orange icon] Long wait to cross 
• [red icon] Red light running 
• [pink icon] Jaywalking 
• [light green icon] Poor visibility 
• [purple icon] Speeding 
• [blue icon] Long distance to cross 
• [yellow icon] Failure to yield 
• [cyan] Cicyclist behavior 

<map legend: red shows high crash corridors. Yellow shows major streets>

**Comment by fkh** [comment]
@fitnr do you want the intro text at the top of the ticker? Take a look at the latest on staging.

**Comment by fitnr** [comment]
I think the solution is to combine the About/Map Intro pages into one page, to be labeled 'About'. I'm revising the copy now.

**Comment by fitnr** [comment]
## About page

Every year, approximately 4,000 New Yorkers are seriously injured and more than 250 are killed in traffic crashes. Being struck by a vehicle is the leading cause of injury-related death for children under 14, and the second leading cause for seniors. On average, vehicles seriously injure or kill a New Yorker every two hours.
Vision Zero is the City's goal for ending traffic deaths and injuries on our streets. To accomplish this, we need everyone’s participation and input. Learn more about [Vision Zero](http://nyc.gov/visionzero).
Use this interactive map to share your experiences with city streets. Your knowledge will be used to create a traffic safety plan for each borough that will describe how to make each borough’s streets safer for everyone, whether walking, biking or driving.
[You're also invited to a Vision Zero workshop to share your ideas](http://www.nyc.gov/html/visionzero/pages/dialogue/events.html). Workshops are being held in all five boroughs.

[Logos of NYC DOT, NYPD and TLC, linked to agency sites]. (see http://www.nyc.gov/html/visionzero/pages/home/home.html)

## Map Legend

[red] Pedestrian crash corridors (top 10% of streets in each borough)
[icon] pedestrian fatality (2009-14)
[yellow] Major arterial roads
We’re gathering feedback on these safety conditions:
- [black icon] Not enough time to cross 
- [dark green icon] Double parking 
- [orange icon] Long wait to cross 
- [red icon] Red light running 
- [pink icon] Jaywalking 
- [light green icon] Poor visibility 
- [purple icon] Speeding 
- [blue icon] Long distance to cross 
- [yellow icon] Failure to yield 
- [cyan] Cicyclist behavior

## Twitter share text

I shared my knowledge to help make #VisionZero a reality in NYC [link]

## Facebook share text

I shared my traffic safety knowledge as part of Vision Zero in New York City.
<Image of appropriate icon> [link] 

## Email

[If name]Dear NAME[/if name]
Thank you for sharing your knowledge of City streets. Your involvement is key to making the City safer.
Your input will be part of a Borough-wide Vision Zero traffic safety plan. Each borough’s plan will outline new safety projects and enforcement strategies to address the issues that you and your neighbors have identified.
Vision Zero workshops and town halls are happening throughout the city. [Learn more about upcoming events](http://www.nyc.gov/html/visionzero/pages/dialogue/events.html).
Thanks again for your help.
[Logos for DOT, NYPD, TLC]

**Comment by fkh** [comment]
@fitnr please confirm that you want the legend to be in sentence case (e.g Poor visibility, not Poor Visibility)

**Comment by fitnr** [comment]
Yes. I am against sentence case creep.

**Comment by fkh** [comment]
I Am With You On That, @fitnr.
