### ISSUE TITLE
Show high-crash corridors on map

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-vision-zero#8]

**Comment by fkh** [comment]
First draft of tiles are here -- https://a.tiles.mapbox.com/v3/openplans.i1m3o54j/page.html?secure=1#16/40.7178/-73.9917

**Comment by fkh** [comment]
- Keep the fatals and the high-crashes to the same color. Red circles with a black border. Dots larger.
- Change the fatal crashes to be differentiated -- maybe a square, or a starburst.
- Try a satellite base layer
- Put a shaded area over everything except the city.

**Comment by fkh** [comment]
@fitnr here's what a satellite basemap could look like. https://a.tiles.mapbox.com/v3/openplans.i23eep2e/page.html?secure=1#16/40.7246/-73.9927

**Comment by fitnr** [comment]
Thanks for mocking up. I think that this is too visually distracting, and we should stick with the map for now.

**Comment by fkh** [comment]
Ok. City-wide tiles are uploading now.
